@echo off
REM Wrapper for starting backend - avoids PowerShell 7.5.4 RemoteException
REM This file is auto-generated by start-all.ps1 with the correct PowerShell executable
REM If you edit this manually, start-all.ps1 will regenerate it on next run
cd /d "%~dp0\.."
REM Try pwsh.exe (PowerShell 7+) first, fallback to powershell.exe (Windows PowerShell 5.1)
where pwsh.exe >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    pwsh.exe -NoExit -ExecutionPolicy Bypass -NoProfile -File "%~dp0start_backend_silent.ps1"
) else (
    powershell.exe -NoExit -ExecutionPolicy Bypass -NoProfile -File "%~dp0start_backend_silent.ps1"
)
